facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
email: "eddy94ug@gmail.org"
name: "Muzinge"
location: Kampala
phone: +974 300-87175
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
