facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
email: "eddyug94@gmail.com"
name: "Kiwanuka"
location: Kampala
phone: +974 3008 7175
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
