color: "#006400"
copyright: "Copyright &copy; 2022 Muzinge. All Rights Reserved."
TermsAndPrivacy:
  company_name: Muzinge 
  contact_email: eddyug94@gmail.com 
  website: muzinge.netlify.app 
  contact_dpo_email: dpo@hugoinaction.com 
  contact_dpo_phone: 9999999999
FormspreeCommentForm: xpzozyyg  
