color: "#006400"
copyright: "Copyright &copy; 2022 Muzinge. All Rights Reserved."
TermsAndPrivacy:
  company_name: Muzinge 
  contact_email: 3754.ngezimu@gmail.com 
  website: muzinge.netlify.app 
  contact_dpo_email: dpo@hugoinaction.com 
  contact_dpo_phone: +974 30087175
FormspreeCommentForm: xjvdondv  
